<?php
declare(strict_types=1);

/*
<strong>Module:</strong>        Practice &raquo;
<strong>Controller:</strong>    Practice &raquo;
<strong>Action:</strong>        index
*/
?>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="jumbotron">
                <h1>Prectice lesson 1</h1>
                <p>Parse a CSV from a URL</p>
                <p><a href="/practice/step1" class="btn btn-primary btn-lg">Check it out</a></p>
            </div>
        </div>
    </div>
</div>
