<?php
declare(strict_types=1);

// Step 1: Parse some CSV
?>
<input type="hidden" id="moduleName" value="practice"/>
<input type="hidden" id="pageName" value="step1"/>

<div>
    <form action="parse" method="post">
        <div class="form-group">
            <label for="inputUrl">CSV URL</label>
            <input type="text" class="form-control" id="inputUrl" placeholder="CSV URL"
                   value="https://admin.b2b-carmarket.com//test/project">
        </div>
        <button type="button" class="btn btn-primary parseAction">Parse</button>
        <button type="button" class="btn importAction" data-action="import-db">Import to DB</button>
        <button type="button" class="btn fakeBuyerNamesAction" data-action="fakeBuyerNames">Fake Buyer</button>
        <button type="button" class="btn step2Action" data-action="step2">Paginated table</button>
    </form>
</div>
<div>
    <img id="loader" src="/img/loader.png" width="420" height="420" style="display: none;">
</div>
<div id="parsedDataTable" style="display: none;">
    <table class="table">
        <thead>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
